sudo: true
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - osx
env:
  - RUST_BACKTRACE=1
install:
  - sh install_rustfmt_clippy.sh
before_script:
  - rustc --version
  - cargo --version
script:
  - cargo build --verbose
  - sh run_tests.sh
  - sh run_sanitizers.sh
after_failure:
  - ls -lat $HOME/Library/Logs/DiagnosticReports/
  - find $HOME/Library/Logs/DiagnosticReports
    -type f
    -name '*.crash'
    -exec printf travis_fold":start:crashlog\n\033[31;1m%s\033[0m\n" {} \;
    -exec head -750 {} \;
    -exec echo travis_fold":"end:crashlog \; || true
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
